name: PrestaFlow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  default:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
          git config --global --add safe.directory /app

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: gd
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_PRESTAFLOW_PS_VERSION: "9.0.0"
        envkey_PRESTAFLOW_LOCALE: "fr"
        file_name: .env

    - name: Run test suite
      run: composer run prestaflow:tests

  drafts:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
          git config --global --add safe.directory /app

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: gd
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_PRESTAFLOW_PS_VERSION: "9.0.0"
        envkey_PRESTAFLOW_LOCALE: "fr"
        file_name: .env

    - name: Run test suite (Draft)
      run: composer run prestaflow:base -- --draft
    - name: Run test suite (Draft)
      run: composer run prestaflow:base -- --no-draft

  groups:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
          git config --global --add safe.directory /app

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: gd
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_PRESTAFLOW_PS_VERSION: "9.0.0"
        envkey_PRESTAFLOW_LOCALE: "fr"
        file_name: .env

    - name: Run test suite
      run: composer run prestaflow:base -- --group=tutorial --group=en

  json:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
          git config --global --add safe.directory /app

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: gd
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_PRESTAFLOW_PS_VERSION: "9.0.0"
        envkey_PRESTAFLOW_LOCALE: "fr"
        file_name: .env

    - name: Run test suite
      run: composer run prestaflow:base -- --output="JSON"
